# Dockerfile.airflow
# Versão: 1.1
# Descrição: Cria uma imagem customizada para o Apache Airflow com dependências específicas

# Dockerfile.airflow
FROM apache/airflow:2.9.2

# Ativar modo de build oficial do Airflow
ENV AIRFLOW_IMAGE_BUILD=true

# Copiar os requirements
COPY requirements.txt /requirements.txt

# Instalar como root (liberado com a flag acima)
RUN pip install --no-cache-dir -r /requirements.txt



