-- INSERTS para a tabela public."tb_habilitacao" com version_id = 1

INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0101', 'Centro de referência em atenção a saúde do idoso', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0202', 'Unidade de alta complexidade ao paciente portador de obesidade grave', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0203', 'Assistência em Alta Complexidade ao individuo com Obesidade', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0301', 'Centros/Núcleos para realização de implante coclear', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0305', 'Atenção Especializada às Pessoas com Deficiência Auditiva', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0401', 'Centro de tratamento da má formação labio-palatal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0403', 'Centro de Especialidade Odontológica - CEO Tipo I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0404', 'Centro de Especialidade Odontológica - CEO Tipo II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0405', 'Centro de Especialidade Odontológica - CEO Tipo III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0406', 'Serviço de Especialidade em Saúde Bucal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0503', 'Unidade de Atenção Especializada em Oftalmologia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0504', 'Centro de Referência em Oftalmologia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0505', 'Projeto Olhar Brasil', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0506', 'Tratamento do Glaucoma com medicamentos no âmbito da Política Nacional de Atenção Oftalmológica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0507', 'Consultório Itinerante de Ensino em Oftalmologia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0508', 'Tratamento do Glaucoma com medicamentos do Componente Especializado da Assistência Farmacêutica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0601', 'Psiquiatria - Classe I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0602', 'Psiquiatria - Classe II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0603', 'Psiquiatria - Classe III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0604', 'Psiquiatria - Classe IV', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0605', 'Psiquiatria - Classe V', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0606', 'Psiquiatria - Classe VI', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0607', 'Psiquiatria - Classe VII', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0608', 'Psiquiatria - Classe VIII', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0609', 'Psiquiatria - Classe IX', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0610', 'Psiquiatria - Classe X', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0611', 'Psiquiatria - Classe XI', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0612', 'Psiquiatria - Classe XII', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0613', 'Psiquiatria - Classe XIII', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0614', 'Psiquiatria - Classe XIV', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0615', 'PNASS maior que 80%', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0616', 'Centro de Atenção Psicossocial - CAPS I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0617', 'Centro de Atenção Psicossocial - CAPS II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0618', 'Centro de Atenção Psicossocial - CAPS III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0619', 'Centro de Atenção Psicossocial Álcool e Drogas - CAPSad', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0620', 'Centro de Atenção Psicossocial Infantil - CAPSi', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0621', 'Serviço hospitalar de referência para a atenção integral aos usuários de álcool e outras drogas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0622', 'Psiquiatria Classe I - PT/GM nº251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0623', 'Psiquiatria Classe II - PT/GM nº251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0624', 'Psiquiatria Classe III - PT/GM nº251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0625', 'Psiquiatria Classe IV - PT/GM nº 251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0626', 'Psiquiatria Classe V - PT/GM nº251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0627', 'Psiquiatria Classe VI - PT/GM nº251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0628', 'Psiquiatria Classe VII - PT/GM nº251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0629', 'Psiquiatria Classe VIII - PT/GM nº251/02', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0630', 'Psiquiatria III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0631', 'Nível I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0632', 'Nível II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0633', 'Nível III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0634', 'Nível IV', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0635', 'Centro de Atenção Psicossocial Álcool e Drogas - CAPS AD III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0636', 'Atenção a pessoas com sofrimento ou transtorno mental decorrente de alcool e outras drogas.', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0637', 'CAPS AD IV', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0801', 'Unidade de assistência de alta complexidade cardiovascular', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0802', 'Centro de referência em alta complexidade cardiovascular', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0803', 'Cirurgia cardiovascular e procedimentos em cardiologia intervencionista', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0804', 'Cirurgia cardiovascular pediátrica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0805', 'Cirurgia vascular', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0806', 'Cirurgia vascular e procedimentos endovasculares extracardíacos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0807', 'Laboratório de eletrofisiologia, cirurgia cardiovascular e procedimentos de cardiologia intervencionista', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0808', 'Implante de marcapasso definitivo', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0809', 'Cirurgia cardíaca', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0810', 'Laboratório eletrofisiológico e terapia intervencionista', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0811', 'QualiSUS Cardio Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0812', 'QualiSUS Cardio Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0813', 'QualiSUS Cardio Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0814', 'QualiSUS Cardio Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0815', 'Implante Percutâneo de Válvula Aórtica (TAVI)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0901', 'Cuidados prolongados - enfermidades cardiovasculares', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0902', 'Cuidados prolongados - enfermidades pneumológicas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0903', 'Cuidados prolongados - enfermidades neurológicas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0904', 'Cuidados prolongados - enfermidades osteomuscular e do tecido conjuntivo', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0905', 'Cuidados prolongados - enfermidades oncológicas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0906', 'Cuidados prolongados - enfermidades decorrentes da AIDS', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0907', 'Cuidados prolongados - enfermidades devido a causas externas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0908', 'Unidade de Internação em Cuidados Prolongados (UCP)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('0909', 'Hospital Especializado em Cuidados Prolongados (HCP)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1001', 'Centro de referência no tratamento da dor crônica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1101', 'Serviço hospitalar para tratamento AIDS', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1102', 'Laboratório Especializado em Contagem de Linfócitos T CD4+/CD8+ e HIV1 Quant. do RNA', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1103', 'Tratamento da lipoatrofia facial do portador de HIV/AIDS', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1104', 'Tratamento da liopodistrofia do Portador de HIV/AIDS', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1105', 'Laboratório Especializado em Contagem de Linfócitos T CD4+/CD8+', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1106', 'Laboratório Especializado em Quantificação do RNA do HIV1', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1201', 'Fibrose cística - Hospital Dia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1202', 'Hospital Dia - Procedimentos cirúrgicos, diagnósticos ou terapêuticos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1203', 'Hospital Dia - AIDS', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1204', 'Hospital Dia em intercorrências pós-transplante de medula óssea e de outros precursores hematopoéticos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1205', 'Hospital Dia - Geriatria', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1206', 'Hospital Dia - Saúde Mental', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1301', 'Internação domiciliar', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1401', 'Referência hospitalar em atendimento secundário a gestante de alto risco', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1402', 'Referência hospitalar em atendimento terciário a gestante de alto risco', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1403', 'Unidade que realiza assistência ao parto sem distócia por enfermeiro obstetra ou obstetriz', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1404', 'Hospital Amigo da Criança', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1405', 'Centro de referência em triagem neonatal/acompanhamento e tratamento de doenças congênitas - fenilcetonuria/hipotireoidismo congenito', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1406', 'Centro de referência em triagem neonatal/acompanhamento e tratamento - doenças falciformes e outras hemoglobinopatias', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1407', 'Centro de referência em triagem neonatal/acompanhamento e tratamento - fibrose cística', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1408', 'Referência em Triagem Neonatal Etapa I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1409', 'Diagnóse de Fibrose Cistica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1410', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo I 3 PPP', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1411', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo I 5 PPP', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1412', 'Unidade de Centro de Parto Normal Peri-Hospitalar 5 PPP', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1413', 'Atenção Hospitalar de Referência à Gestação de Alto Risco Tipo 1', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1414', 'Atenção Hospitalar de Referência à Gestação de Alto Risco Tipo 2', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1415', 'Casa da Gestante, Bebê e Puérpera', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1416', 'Hospital Amigo da Criança', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1417', 'Unidade de Centro de Parto Normal Peri-Hospitalar 3 PPP', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1418', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo II 3 PPP', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1419', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo II 5 PPP', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1501', 'Unidade de assistência de alta complexidade em nefrologia (serviço de nefrologia)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1502', 'Centro de referência de alta complexidade em nefrologia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1504', 'Atenção Especializada em DRC com Hemodiálise', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1505', 'Atenção Especializada em DRC com Diálise Peritoneal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1506', 'Atenção Especializada em DRC nos estágios 4 e 5-PréDialitico', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1507', 'Unidade Especializada em DRC com TRS/Diálise Tipo I com Hemodiálise', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1508', 'Unidade Especializada em DRC com TRS/Diálise Tipo I com Diálise Peritoneal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1509', 'Unidade Especializada em DRC com TRS/Diálise Tipo II com Hemodiálise', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1510', 'Unidade Especializada em DRC com TRS/Diálise Tipo II com Diálise Peritoneal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1511', 'Unidade Especializada em DRC com TRS/Diálise Tipo III com Hemodiálise', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1512', 'Unidade Especializada em DRC com TRS/Diálise Tipo III com Diálise Peritoneal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1513', 'Unidade Especializada em DRC com TRS/Diálise Tipo IV com Hemodiálise', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1514', 'Unidade Especializada em DRC com TRS/Diálise Tipo IV com Diálise Peritoneal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1601', 'Unidade de assistência de alta complexidade em neurologia/neurocirurgia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1602', 'Centro de referência de alta complexidade em neurologia/neurocirurgia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1603', 'Trauma e anomalias do desenvolvimento', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1604', 'Coluna e dos nervos periféricos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1605', 'Tumores do sistema nervoso', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1606', 'Neurocirurgia vascular', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1607', 'Tratamento neurocirúrgico da dor e funcional', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1608', 'Investigação e cirurgia de epilepsia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1609', 'Tratamento neuro-endovascular', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1610', 'Neurocirurgia funcional esteriotáxica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1611', 'Epilepsia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1612', 'Neurocirurgia I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1613', 'Neurocirurgia II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1614', 'Neurocirurgia III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1615', 'Centro de Atendimento de Urgência Tipo I aos Pacientes com AVC', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1616', 'Centro de Atendimento de Urgência Tipo II aos Pacientes com AVC', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1617', 'Centro de Atendimento de Urgência Tipo III aos Pacientes com AVC', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1618', 'Neurocirurgia Endovascular/Trombectomia Mecanica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1704', 'Serviço isolado de radioterapia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1705', 'Serviço isolado de quimioterapia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1706', 'UNACON', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1707', 'UNACON com serviço de radioterapia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1708', 'UNACON com serviço de hematologia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1709', 'UNACON com serviço de oncologia pediátrica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1710', 'UNACON exclusiva de hematologia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1711', 'UNACON exclusiva de oncologia pediátrica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1712', 'CACON', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1713', 'CACON com serviço de oncologia pediátrica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1714', 'Hospital Geral com cirurgia oncológica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1715', 'Serviço de radioterapia de complexo hospitalar', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1716', 'Serviço de Oncologia Clínica de Complexo hospitalar', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1717', 'Oncologia Cirúrgica Hospital Porte A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1718', 'Oncologia Cirúrgica Hospital Porte B.', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1719', 'Serviço de Referência P/Diagnóstico e Trat. de Lesões Precursoras do Câncer do Colo de Útero(SRC)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1720', 'Serviço de Referência para Diagnóstico de Câncer de Mama (SDM)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1721', 'Hospital Geral com Cirurgia de Câncer de Complexo Hospitalar', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1722', 'Tratamentos Integrados Sincrônicos em Oncologia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1723', 'Reconstrução Mamária Pós-Mastectomia Total', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1801', 'Centro de referência de tratamento de osteogênesis imperfecta', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1901', 'Laqueadura', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('1902', 'Vasectomia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2001', 'Programa de assistência ventilatoria não invasiva aos portadores de doenças neuromusculares', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2101', 'Unidade de referência em assistência a queimados - média complexidade', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2102', 'Centro de referência em assistência a queimados - alta complexidade', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2201', 'Centro de referência de reabilitação em medicina fisica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2202', 'Centro de reabilitação fisica - nível intermediário', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2203', 'Centro de Reabilitação Visual', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2204', 'Centro de Reabilitação Auditiva na Média Complexidade', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2205', 'Centro de Reabilitação Auditiva na Alta Complexidade', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2206', 'Centro de Reabilitação Intelectual', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2207', 'Centro de Reabilitação dos Transtornos do Spectro do Autismo', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2208', 'Centro Especializado em Reabilitação (CER) Modalidade Física', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2209', 'Centro Especializado em Reabilitação (CER) Modalidade Intelectual', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2210', 'Centro Especializado em Reabilitação (CER) Modalidade Auditiva', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2211', 'Centro Especializado em Reabilitação (CER) Modalidade Visual', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2212', 'Oficina Ortopédica Fixa', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2213', 'Oficina Ortopédica Intínerante', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2301', 'Unidade de assistência de alta complexidade em terapia nutricional', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2302', 'Centro de referência de alta complexidade em terapia nutricional', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2303', 'Enteral', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2304', 'Enteral e parenteral', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2305', 'Enteral e parenteral com manipulação e fabricação da fórmula nutricional', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2306', 'Nutrição enteral', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2308', 'Serviço de Referência em Tratamento da Pessoa com Falência Intestinal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2401', 'Transplante de medula óssea-autogênico', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2402', 'Transplante de medula óssea-alogênico aparentado', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2403', 'Transplante de medula óssea-alogênico não aparentado', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2404', 'Transplante de pâncreas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2405', 'Transplante conjugado rim e pâncreas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2407', 'Transplante de córnea/esclera', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2408', 'Transplante de rim', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2409', 'Transplante de fígado', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2410', 'Transplante de pulmão', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2411', 'Transplante de coração', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2412', 'Busca ativa de orgãos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2413', 'Banco de tecido ocular humano', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2414', 'Banco de válvulas cardíacas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2415', 'Banco de tecido músculo-esquelético', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2416', 'Banco de sangue e cordão umbilical e placentário', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2417', 'Exames de histocompatibilidade atraves de sorologia - Tipo I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2418', 'Exames de histocompatibilidade atraves de sorologia e ou biologia molecular - Tipo II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2419', 'Banco de Pele Humana', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2420', 'Retirada de Órgãos e Tecidos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2421', 'Banco de Multitecidos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2422', 'Transplante de tecido músculo esquelético', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2423', 'Transplante da válvula cardíaca humana', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2424', 'Transplante de pele', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2425', 'Cadastramento de doadores voluntários de medula óssea e outros precursores hematopoéticos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2426', 'Estabelecimento de saúde de Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2427', 'Estabelecimento de saúde de Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2428', 'Estabelecimento de saúde de Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2429', 'Estabelecimento de saúde de Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2430', 'Transplante de figado - IHH por febre amarela', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2431', 'QUALIDOT Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2432', 'QUALIDOT Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2433', 'QUALIDOT Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2434', 'QUALIDOT Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2435', 'QUALIDOT Nível E', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2436', 'Incremento Financeiro SNT TMO Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2437', 'Incremento Financeiro SNT TMO Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2438', 'Incremento Financeiro SNT TMO Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2439', 'Incremento Financeiro SNT TMO Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2440', 'Incremento Financeiro SNT TMO Nível E', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2441', 'Incremento Financeiro SNT Pâncreas Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2442', 'Incremento Financeiro SNT Pâncreas Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2443', 'Incremento Financeiro SNT Pâncreas Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2444', 'Incremento Financeiro SNT Pâncreas Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2445', 'Incremento Financeiro SNT Pâncreas Nível E', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2446', 'Incremento Financeiro SNT Rim Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2447', 'Incremento Financeiro SNT Rim Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2448', 'Incremento Financeiro SNT Rim Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2449', 'Incremento Financeiro SNT Rim Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2450', 'Incremento Financeiro SNT Rim Nível E', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2451', 'Incremento Financeiro SNT Fígado Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2452', 'Incremento Financeiro SNT Fígado Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2453', 'Incremento Financeiro SNT Fígado Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2454', 'Incremento Financeiro SNT Fígado Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2455', 'Incremento Financeiro SNT Fígado Nível E', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2456', 'Incremento Financeiro SNT Pulmão Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2457', 'Incremento Financeiro SNT Pulmão Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2458', 'Incremento Financeiro SNT Pulmão Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2459', 'Incremento Financeiro SNT Pulmão Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2460', 'Incremento Financeiro SNT Pulmão Nível E', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2461', 'Incremento Financeiro SNT Coração Nível A', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2462', 'Incremento Financeiro SNT Coração Nível B', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2463', 'Incremento Financeiro SNT Coração Nível C', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2464', 'Incremento Financeiro SNT Coração Nível D', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2465', 'Incremento Financeiro SNT Coração Nível E', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2466', 'Transplante de intestino delgado ou multivisceral', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2501', 'Unidade de atenção especializada em traumato-ortopedia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2502', 'Centro de referência de alta complexidade em traumato-ortopedia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2503', 'Coluna', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2504', 'Cintura escapular, ombro, braço e cotovelo', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2505', 'Antebraço, punho e mão', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2506', 'Cintura pélvica, quadril, coxa', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2507', 'Coxa, joelho e perna', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2508', 'Perna, tornozelo e pé', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2509', 'Ortopedia infantil', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2510', 'Traumatologia ortopédica de urgência', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2511', 'Ortopedia - Coluna', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2512', 'Ortopedia - Ombro', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2513', 'Ortopedia - Mão', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2514', 'Ortopedia - Quadril', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2515', 'Ortopedia - Joelho', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2516', 'Ortopedia - Tumor Ósseo', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2517', 'Outros segmentos ósseos', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2518', 'Adesão á Estratégia de Aumento do Acesso aos Procedimentos-TOM', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2601', 'UTI II - Adulto', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2602', 'UTI II - Neonatal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2603', 'UTI II - Pediátrica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2604', 'UTI III - Adulto', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2605', 'UTI III - Neonatal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2606', 'UTI III - Pediátrica', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2607', 'UTI - Queimados', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2608', 'Unidade Terapia Intensiva Coronariana - UCO TIPO II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2609', 'Unidade Terapia Intensiva Coronariana - UCO TIPO III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2610', 'Unidade de Terapia Intensiva Neonatal Tipo II - UTIN II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2611', 'Unidade de Terapia Intensiva Neonatal Tipo III - UTIN III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2612', 'UTI II Adulto - Síndrome Respiratória Aguda Grave (SRAG) - COVID-19', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2613', 'UTI II Pediátrica - Síndrome Respiratória Aguda Grave (SRAG) - COVID-19', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2696', 'UTI I Adulto', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2697', 'UTI I Neonatal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2698', 'UTI I Pediatria', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2699', 'UTI I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2701', 'Hospital Tipo I em Urgência', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2702', 'Hospital Tipo II em Urgência', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2703', 'Hospital Tipo III em Urgência', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2711', 'Administração Pré Hospitalar de Tenectoplase', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2801', 'Unidade de cuidados intermediários neonatal', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2802', 'Unidade de Cuidados Intermediários Neonatal Convencional (UCINCo)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2803', 'Unidade de Cuidados Intermediários Neonatal Canguru (UCINCa)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2804', 'Unidade de Cuidados Intermediários Adulto', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2805', 'Unidade de Cuidados Intermediários Pediátrica (UCI-P)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2806', 'Leito de Suporte Ventilatório Pulmonar-COVID-19', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2901', 'Videocirurgia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('2902', 'Programa Mais Acesso a Especialistas - Componente Cirurgias', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3001', 'Unidade de Atenção Especializada no Processo Transexualizador', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3002', 'Atenção ao Pré e Pós Operatório (clínico) e Hormonioterapia no Processo Transexualizador', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3003', 'Atenção ao Pré e Pós Operatório e Cirurgias no Processo Transexualizador', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3101', 'HPP- Hospital de Pequeno Porte', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3201', 'Unidade de Mamografia Móvel', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3202', 'Laboratório de Exames Citopatológico do Cólo do Últero-Tipo I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3203', 'Lab. Monitoramento Externo de Qualidade de Exame Citopatológico do Colo do Útero Tipo-II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3401', 'Centro de Trauma Tipo I', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3402', 'Centro de Trauma Tipo II', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3403', 'Centro de Trauma Tipo III', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3501', 'Atenção Especializada Eixo I DR de Origem Genética: 1-Anomalias Congênitas ou de Manifestação Tardia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3502', 'Atenção Especializada Eixo I DR de Origem Genética:2-Deficiência Intelectual Associada à Doença Rara', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3503', 'Atenção Especializada Eixo I DR de Origem Genética: 3-Erro Inato do Metabolismo (EIM)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3504', 'Atenção Especializada Eixo II DR de Origem não Genética: 1-Doenças Raras Inflamatórias', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3505', 'Atenção Especializada Eixo II DR de Origem não Genética: 2-Doenças Raras Infecciosas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3506', 'Atenção Especializada Eixo II DR de Origem não Genética: 3-Doenças Raras Autoimunes', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3507', 'Serviço de Referência Eixo I DR de Origem Genética:1 Anomalias Congênitas ou de Manifestação Tardia', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3508', 'Serviço de Referência Eixo I DR de Origem Genética:2-Deficiência Intelectual Associada à Doença Rara', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3509', 'Serviço de Referência Eixo I DR de Origem Genética:3-Erro Inato do Metabolismo (EIM)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3510', 'Serviço de Referência Eixo II DR de Origem não Genética:3-Doenças Raras Autoimunes', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3511', 'Serviço de Referência Eixo II DR de Origem não Genética:2-Doenças Raras Inflamatórias', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3512', 'Serviço de Referência Eixo II DR de Origem não Genética:1-Doenças Raras Infecciosas', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3513', 'Atenção Especializada Eixo II DR de Origem não Genética:4-Outras DR de Origem não Genética', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3514', 'Serviço de Referência Eixo II DR de Origem não Genética:4-Outras DR de Origem não Genética', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3515', 'Serviço de Aconselhamento Genético', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3601', 'Sítio Testador de ácidos nucléicos (SIT-NAT)', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3701', 'Coleta de Vestígios de Violência Sexual', '202507', 1);
INSERT INTO public."tb_habilitacao" ("co_habilitacao", "no_habilitacao", "dt_competencia", "version_id") VALUES ('3801', 'Programa Mais Acesso a Especialistas', '202507', 1);
