-- INSERTS para a tabela public."tb_rubrica" com version_id = 1

INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040009', 'Atendimento/acompanhamento em reabilitação física, mental, visual, auditiva e múltiplas deficiências', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040013', 'Atendimento/acompanhamento de diagnóstico de doenças endocrinas/metabólicas e nutricionais', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040017', 'Nefrologia', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040024', 'Cirurgia do aparelho digestivo, orgãos anexos e parede abdominal(inclui pré e pós operatório)', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040028', 'Outras cirurgias plásticas/reparadoras', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040030', 'Sequenciais', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040032', 'Transplantes de orgãos, tecidos e células', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040033', 'Medicamentos para transplante', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040038', 'OPM para transplantes', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040041', 'Central Nacional de Regulação de Alta Complexidade (CNRAC)', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040044', 'Redesignação e Acompanhamento', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040049', 'Implementar Cirg. CV Pediátrica', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040055', 'Transplante - Histocompatibilidade', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040062', 'Doenças Raras', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040063', 'Cadeiras de Rodas', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040065', 'Medicamentos em Urgência', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040066', 'Cirurgias Eletivas - Componente Único', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040067', 'Atenção Especializada em Saúde Auditiva', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040068', 'Terapias Especializadas em Angiologia', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040069', 'Tratamento de Doença Macular', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040070', 'OPME Não Relacionados ao Ato Cirúrgico', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040071', 'Diagnóstico/tratamento em oncologia', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040072', 'Diagnóstico de trombofilia em gestante', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040073', 'Reabilitação Pós-COVID-19', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040074', 'Telemedicina em Urgência', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040075', 'Fisioterapia Cardiovascular', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040076', 'Hemodinâmica em atendimento de urgência', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040077', 'Exames Sorológicos e Imunológicos', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040078', 'QualiSUS Cardio', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040079', 'Pré-cirúrgico em Cirurgias Prioritárias', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040080', 'Redução das Filas de Procedimentos Eletivos.', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040081', 'Síndrome Respiratória Aguda Grave - SRAG', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040082', 'Alta Complexidade em Cardiologia', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040083', 'Cirurgia da Face e do Sistema Estomatognático', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040084', 'Neurocirurgias', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040085', 'Exames coprológicos', '202507', 1);
INSERT INTO public."tb_rubrica" ("co_rubrica", "no_rubrica", "dt_competencia", "version_id") VALUES ('040086', 'Programa Mais Acesso a Especialistas (PMAE)', '202507', 1);
