-- INSERTS para a tabela public."tb_regra_condicionada" com version_id = 1

INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0004', 'CONDICIONA INCREMENTO POR CID EXCLUSIVOS', 'QUANDO OS PROCEDIMENTOS  DE CÓDIGOS (02.09.01.003-7, 02.05.02.004-6, 02.05.01.003-2, 02.05.01.004-0 E 02.11.08.005-5) FOREM REGISTRADOS COM OS CID E66.0, E66.2, E66.8 E E66.9,  NA MODALIDADE AMBULATORIAL E O ESTABELECIMENTO DE SAÚDE POSSUIR HABILITAÇÃO 02.03,  O TIPO DE FINANCIAMENTO PASSA A SER  FAEC COM O SUBTIPO DE FINANCIAMENTO 0024', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0006', 'CONDICIONA A REJEIÇÃO DA AIH - ORTOPEDIA', 'Caso haja duplicidade de AIH na mesma competência de processamento no SIHD e um dos procedimentos principais for o de código 0415020069 PROCEDIMENTOS SEQUENCIAIS EM ORTOPEDIA ou quaisquer outro iniciado por 0408, caberá ao gestor aprovar apenas uma destas AIH.', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0001', 'CONDICIONA REGISTRO EM BPA-I (CEO E PCD)', 'ATENDIMENTO ODONTOLÓGICO À PESSOA COM DEFICIÊNCIA (PCD) REALIZADO EM CENTRO DE ESPECIALIDADES ODONTOLÓGICAS (CEO) HABILITADOS (0403,0404 OU 0405) DEVERÁ SER REGISTRADO EM BPA-I COM PREENCHIMENTO DO CAMPO SERVIÇO 114 CLASSIFICAÇÃO 007', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0007', 'CONDICIONA A REJEIÇÃO DA AIH - NEUROCIRURGIA', 'Caso haja duplicidade de AIH na mesma competência de processamento no SIHD e um dos procedimentos principais for o de código 0415020077 PROCEDIMENTOS SEQUENCIAIS EM NEUROCIRURGIA ou quaisquer outro iniciado por 0403, caberá ao gestor aprovar apenas uma destas AIH.', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0009', 'CONDICIONA AOS SECUDÁRIOS A TEREM VALOR ZERADO', 'OS PROCEDIMENTOS PRINCIPAIS  VINCULADOS A ESTA REGRA TERÃO SEUS PROCEDIMENTOS SECUNDÁRIOS COM VALOR ZERADO.', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0002', 'CONDICIONA O TIPO DE FINANCIAMENTO POR FAEC (POB)', 'PROCEDIMENTO OFTALMOLÓGICO QUANDO REALIZADO EM ESTABELECIMENTO HABILITADO EM |PROJETO OLHAR BRASIL (05.05) E APRESENTADO EXCLUSIVAMENTE NOS SERVIÇOS 131/006 OU 131/007 , O TIPO DE FINANCIAMENTO SERÁ FAEC E APLICA-SE INCREMENTO', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0003', 'CONDICIONA A REJEIÇÃO DA AIH - ONCOLOGIA', 'Caso haja duplicidade de AIH na mesma competência de processamento no SIHD e um dos procedimentos principais for o de código 0415020050 PROCEDIMENTOS SEQUENCIAIS EM ONCOLOGIA, a AIH com data de alta mais recente será a única aprovada.', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0005', 'FINANCIAMENTO POR FAIXA ETÁRIA - MAMOGRAFIA', 'PROCEDIMENTO 02.04.03.018-8 MAMOGRAFIA BILATERAL PARA RASTREAMENTO QUANDO REALIZADO EM PESSOA COM IDADE COMPREENDIDA ENTRE 50 A 69 ANOS, O TIPO DE FINANCIAMENTO SERÁ FAEC.', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0008', 'CONDICIONA A TER O VALOR ZERADO.', 'Procediemnto sem valor quando apresentado como  APAC Secundário - VALOR ZERADO', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0012', 'CONDICIONA O TIPO DE FINANCIAMENTO EM FAEC NO PMAE', 'CONDICIONA QUE O PROCEDIMENTO SECUNDÁRIO, QUANDO REALIZADO EM ESTABELECIMENTO HABILITADO NO PROGRAMA MAIS ACESSO A ESPECIALISTAS (CÓDIGO DE HABILITAÇÃO 38.01) E EM APAC COM ROCEDIMENTOPRINCIPAL DO GRUPO 09, TERÁ O TIPO DE FINANCIAMENTO FAEC', 1);
INSERT INTO public."tb_regra_condicionada" ("co_regra_condicionada", "no_regra_condicionada", "ds_regra_condicionada", "version_id") VALUES ('0011', 'CONDICIONA O REGISTRO DE PROCEDIMENTOS SECUNDÁRIOS NA APAC', 'Condiciona a obrigatoriedade de serem registrados procedimentos secundários executados em APAC, obedecendo as compatibilidades estabelecidas em portaria.', 1);
