-- INSERTS para a tabela public."tb_renases" com version_id = 1

INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('001', 'Gestão da Atenção Primária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('002', 'Atenção Domiciliar', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('003', 'Atendimento Cirúrgico Ambulatorial Básico', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('004', 'Atendimento Clinico na Atenção Primária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('005', 'Consulta e Acompanhamento Realizados por Profissional de Nível Superior', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('006', 'Exames Diagnósticos na Atenção Primária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('007', 'Práticas Integrativas e Complementares', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('008', 'Ações Comunitárias', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('009', 'Atenção Familiar', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('010', 'Atividades Educativas, Terapêuticas e de Orientação à População.', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('011', 'Atividades Físicas, Educativas e de Orientação à População.', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('012', 'Imunização', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('013', 'Visita Domiciliar ou Institucional', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('014', 'Atenção à Saúde da Criança', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('015', 'Atenção à Saúde da Mulher', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('016', 'Atenção à Saúde de Pessoas com Doenças Transmissíveis Epidemiologicamente Relevantes para o País', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('017', 'Atenção à Saúde do Adolescente', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('018', 'Atenção à Saúde do Homem', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('019', 'Atenção à Saúde do Idoso', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('020', 'Atenção à Saúde dos Adultos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('021', 'Atenção a Saúde Mental, Ácool e Outras Drogas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('022', 'Educação em Saúde sobre Uso Racional de Medicamentos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('023', 'Orientação Farmacêutica na Dispensação de Medicamentos.', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('024', 'Realização de Procedimentos Cirúrgicos  em Saúde Bucal', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('025', 'Realização de Procedimentos Clínicos em Saúde Bucal', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('026', 'Atenção à Saúde da Pessoa com Deficiência', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('027', 'Gestão de Serviços de Urgência e Emergência', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('028', 'Atendimento de Urgência em Unidades Básicas de Saúde', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('029', 'Atendimento de Urgência em Unidades de Pronto Atendimento 24 horas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('030', 'Atendimento de Urgência em Unidades Hospitalares', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('031', 'Atendimento em Sala de Estabilização', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('032', 'Atendimento Pré-hospitalar de Urgência para Gestantes, Puérperas e Recém-Nascidos de Alto Risco', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('033', 'Atendimento Pré-hospitalar Móvel de Urgência', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('034', 'Gestão da Rede de Atenção Psicossocial', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('035', 'Acolhimento e Atenção de Retaguarda para Usuários de Àlcool e Drogas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('036', 'Alta Planejada e Reabilitação Psicossocial Assistida', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('037', 'Aplicação de Testes (psicodiagnósticos)', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('038', 'Atenção Psicossocial - Centros de Atenção Psicossocial', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('039', 'Atenção Psicossocial Hospitalar', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('040', 'Atividades Educativas Coletivas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('041', 'Diagnóstico em Psicologia e Psiquiatria', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('042', 'Geração de Trabalho e Renda', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('043', 'Residências Terapêuticas para Egressos de Hospitais Psiquiátricos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('044', 'Terapia em Grupo', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('045', 'Terapia Individual', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('046', 'Tratamento dos Transtornos Mentais e Comportamentais', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('047', 'Gestão da Atenção Especializada', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('048', 'Acompanhamento e Tratamento de Doenças ou Condições Clínicas Crônicas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('049', 'Assistência Domiciliar Terapêutica Multiprofissional em HIV/AIDS (ADTM)', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('050', 'Assistência Especializada Domiciliar Realizada por Equipe Multiprofissional', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('051', 'Atenção à Saúde de Pessoas Privadas de Liberdade', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('052', 'Atendimento e Acompanhamento de Pacientes Acometidos por Anemia Falciforme e Outras Hemoglobinopatias', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('053', 'Atendimento e Acompanhamento de Pacientes Acometidos por Doeças Endócrinas, Metabólicas ou Nutricionais', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('054', 'Atendimento e acompanhamento de pacientes com depressão pós-parto', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('055', 'Atendimento e Acompanhamento em Reabilitação de Pessoas com Deficiência', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('056', 'Atividade Educativa ou Orientação em Grupo na Atenção Especializada', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('057', 'Cirurgia Ambulatorial do Sistema Geniturinário: Vasectomia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('058', 'Cirurgias Ambulatoriais com Anestesia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('059', 'Cirurgias Ambulatoriais do Sistema Geniturinário', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('060', 'Cirurgias Ambulatoriais do Sistema Osteomuscular', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('061', 'Cirurgias Ambulatoriais em Nefrologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('062', 'Cirurgias Ambulatoriais: Aparelho Digestivo, Orgãos Anexos e Parede Abdominal', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('063', 'Cirurgias Ambulatoriais: Cirurgia Bucomaxilofacial', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('064', 'Cirurgias Ambulatoriais: Cirurgia do Aparelho Circulatório', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('065', 'Cirurgias Ambulatoriais: Cirurgia Ginecológica e Obstétrica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('066', 'Cirurgias Ambulatoriais: Cirurgia Plástica Reparadora', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('067', 'Cirurgias Ambulatoriais: Cirurgia Torácica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('068', 'Cirurgias Ambulatoriais: Cirurgias da Mama', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('069', 'Cirurgias Ambulatoriais: Cirurgias Reparadoras para Tratamentos de Grandes Queimados e Pacientes com Lipoatrofia de Face', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('070', 'Cirurgias Ambulatoriais: Oftalmológicas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('071', 'Cirurgias Ambulatoriais: Pele, Tecidos Subcutâneos e Mucosas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('072', 'Cirurgias Ambulatoriais: Vias Respiratórias', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('073', 'Coleta de Material para Exame Complementar ao Diagnóstico, por Meio de Punção ou Biópsia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('074', 'Consultas Eletivas Especializadas, Realizadas por Profissionais de Nível Superior', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('075', 'Diagnóstico por Endoscopia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('076', 'Diagnóstico por Imagem', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('077', 'Diagnóstico por Medicina Nuclear IN VIVO', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('078', 'Diagnóstico por Radiologia Intervencionista', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('079', 'Diagnósticos e Procedimentos Especiais em Hemoterapia: Exames do Doador/Receptor', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('080', 'Diagnósticos e Procedimentos Especiais em Hemoterapia: Procedimentos Especiais em Hemoterápica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('081', 'Diagnósticos por Testes Rápidos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('082', 'Dispensação de Òrteses e Próteses em Caráter Ambulatorial', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('083', 'Exames Anatomopatológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('084', 'Exames Citopatológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('085', 'Exames Citopatológicos para Prevenção do Câncer do Colo Uterino', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('086', 'Exames Complementares de Diagnóstico: Exames Bioquímicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('087', 'Exames Complementares de Diagnóstico: Exames Coprológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('088', 'Exames Complementares de Diagnóstico: Exames de Uroanálise', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('089', 'Exames Complementares de Diagnóstico: Exames Hematológicos e Hemostasia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('090', 'Exames Complementares de Diagnóstico: Exames Microbiológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('091', 'Exames Complementares de Diagnóstico: Exames para Triagem Neonatal', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('092', 'Exames Complementares de Diagnóstico: Exames Sorológicos e Imunológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('093', 'Exames Complementares do Diagnóstico  - Exames em  Liquidos Biológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('094', 'Exames Complementares do Diagnóstico: Exames de Genética', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('095', 'Exames Complementares do Diagnóstico: Exames Imuno-Hematológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('096', 'Exames Hormonais', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('097', 'Exames Toxicológicos ou de Monitorização Terapêutica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('098', 'Hemoterapia: Medicina Transfusional', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('099', 'Hemoterapia: Procedimentos Destinados à Obtenção do Sangue para Fins de Assistência Hemoterápica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('100', 'Métodos Diagnósticos Cinético-Funcionais', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('101', 'Métodos Diagnósticos em Angiologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('102', 'Métodos Diagnósticos em Cardiologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('103', 'Métodos Diagnósticos em Cardiologia Intervencionista', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('104', 'Métodos Diagnósticos em Ginecologia e Obstetrícia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('105', 'Métodos Diagnósticos em Neurologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('106', 'Métodos Diagnósticos em Oftalmologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('107', 'Métodos Diagnósticos em Otorrinolaringologia e Fonoaudiologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('108', 'Métodos Diagnósticos em Pneumologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('109', 'Métodos diagnósticos em psicologia e psiquiatria', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('110', 'Métodos Diagnósticos em Urologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('111', 'Outras Cirurgias Ambulatoriais', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('112', 'Terapia Nutricional', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('113', 'Terapias em doenças alérgicas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('114', 'Terapias em Urologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('115', 'Tratamento em Nefrologia: Tratamento Dialítico', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('116', 'Tratamento Oncológico: Medicina Nuclear - Terapêutica Oncológica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('117', 'Tratamento Oncológico: Quimioterapia Adjuvante Profilática em Adultos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('118', 'Tratamento Oncológico: Quimioterapia Curativa em Adultos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('119', 'Tratamento Oncológico: Quimioterapia de Tumores de Crianças e Adolescentes', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('120', 'Tratamento Oncológico: Quimioterapia Paliativa em Adultos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('121', 'Tratamento Oncológico: Quimioterapia para Controle Temporário de Doença em Adultos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('122', 'Tratamento Oncológico: Quimioterapia Prévia Neoadjuvante ou Citorredutora em Adultos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('123', 'Tratamento Oncológico: Radioterapia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('124', 'Tratamento Oncológico: Tratamento de Intercorrências Clínicas em Paciente Oncológico', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('125', 'Realização de Procedimentos Clínicos em Odontologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('126', 'Realização de procedimentos com finalidade diagnóstica em Odontologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('127', 'Realização de Procedimentos Cirúrgicos em Odontologia Especializada', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('128', 'Atividade Educativa em Saúde Bucal', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('129', 'Confecção de Órteses e Próteses Odontológicas', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('130', 'Laboratório Regional de Prótese Dentária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('131', 'Centro de Especialidade Odontológica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('132', 'Atendimento Odontológico para Pacientes com Necessidades Especiais em Ambientes Hospitalares', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('133', 'Cirurgia do Sistema Osteomuscular', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('134', 'Cirurgia Bucomaxilofacial', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('135', 'Cirurgias Plásticas/Reparadoras', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('136', 'Cirurgia Reparadora para Lipodistrofia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('137', 'Cirurgia Reparadora em Tratamento de Queimados', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('138', 'Cirurgia Geral', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('139', 'Cirurgias em  Politraumatizados', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('140', 'Internações de Longa Permanência', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('141', 'Hospital-Dia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('142', 'Cirurgia em Oncologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('143', 'Intervenções Cirúrgicas para Criação de Acessos para Diálise', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('144', 'Transplantes', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('145', 'Ações Relacionadas a Doação de Orgãos e Tecidos em Doador', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('146', 'Dispensação de Órteses e Próteses e Materiais Especiais em Caráter Hospitalar', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('147', 'Tratamento Intensivo', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('148', 'Acolhimento com Classificação de Risco em Maternidades', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('149', 'Parto Normal em Gravidez de Risco Habitual', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('150', 'Parto Normal em Gestação de Alto Risco', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('151', 'Parto Cesáreo em Gravidez de Risco Habitual', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('152', 'Parto Cesáreo em Gestação de Alto Risco', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('153', 'Parto Cesáreo com Laqueadura Tubária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('154', 'Cirurgia Bariátrica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('155', 'Internação para Tratamento Medicamentoso da Osteogenesis Imperfecta', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('156', 'Cirurgia do Sistema Nervoso Central e Periférico Relacionada ao Trauma e Anomalias do Desenvolvimento', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('157', 'Cirurgia do Sistema Nervoso Central e Periférico Relacionada a Coluna e Nervos Periféricos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('158', 'Cirurgia do Sistema Nervoso Central e Periférico Relacionada aos Tumores do Sistema Nervoso', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('159', 'Cirurgia do Sistema Nervoso Central e Periférico, Relacionada às Neurocirurgias Vasculares', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('160', 'Cirurgia do Sistema Nervoso Central e Periférico, Relacionada ao Tratamento Neurocirúrgico da Dor Funcional', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('161', 'Cirurgia do Sistema Nervoso Central: Investigação e Cirurgia da Epilepsia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('162', 'Cirurgia do Sistema Nervoso Central e Periférico, Relacionada ao Tratamento Neuroendovascular', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('163', 'Cirurgia das Vias Aéreas Superiores, da Face, da Cabeça e do Pescoço', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('164', 'Cirurgia do Aparelho da Visão', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('165', 'Cirurgia Cardiovascular', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('166', 'Cirurgia Vascular', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('167', 'Cardiologia Intervencionista', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('168', 'Cirurgia Endovascular', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('169', 'Eletrofisiologia', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('170', 'Cirurgia do Sistema Nervoso Central - Neurocirurgia Funcional Estereotáxica', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('171', 'Gestão da Vigilância em Saúde', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('172', 'Autorização de Funcionamento de Empresas sujeitas a Vigilância Sanitária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('173', 'Registro, Notificação, Cadastro Sanitário de Produtos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('174', 'Anuência de Importação e Registro de Exportação', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('175', 'Anuência Prévia de Patente', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('176', 'Regulação de Preço de Medicamentos e Produtos para Saúde', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('177', 'Credenciamento e Habilitação de Laboratórios Analíticos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('178', 'Controle Sanitário e Orientação de Viajantes', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('179', 'Monitoramento Sanitário de Produtos e Serviços', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('180', 'Gerenciamento do Risco Sanitário', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('181', 'Análise e Aprovação de Projetos Básicos de Arquitetura', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('182', 'Informação, Educação e Comunicação em Vigilância em Saúde', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('183', 'Acolhimento e Atendimento a Notificações, Denuncias e Reclamações', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('184', 'Regulamentação de Ações de Saúde Pública sob Vigilância Sanitária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('185', 'Fiscalização Sanitária de Produtos e Serviços', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('186', 'Emissão de Certidões e Certificados', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('187', 'Inspeção Sanitária dos Estabelecimentos Sujeitos à Vigilância Sanitária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('188', 'Emissão de Licença Sanitária para Estabelecimentos Sujeitos à Vigilância Sanitária', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('189', 'Farmacovigilância', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('190', 'Alerta e Resposta a Surtos e Eventos de Importância em Saúde Pública', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('191', 'Notificação de Eventos de Interesse de Saúde Pública', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('192', 'Investigação de Eventos de Interesse de Saúde Pública', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('193', 'Busca Ativa', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('194', 'Interrupção da Cadeia de Transmissão', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('195', 'Controle de Vetores, Reservatórios e Hospedeiros.', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('196', 'Diagnóstico Laboratorial de Eventos de Interesse de Saúde Pública', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('197', 'Vacinação', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('198', 'Oferta de Tratamento Clínico e Cirúrgico para Doenças de Interesse de Saúde Pública', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('199', 'Realização de Inquéritos Epidemiológicos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('200', 'Prevenção de Doenças e Agravos', 1);
INSERT INTO public."tb_renases" ("co_renases", "no_renases", "version_id") VALUES ('201', 'Promoção da Saúde', 1);
