-- INSERTS para a tabela public."tb_sub_grupo" com version_id = 1

INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '01', 'Pequenas cirurgias e cirurgias de pele, tecido subcutâneo e mucosa', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('05', '01', 'Coleta e exames para fins de doação de orgãos, tecidos e células e de transplante', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '01', 'Coleta de material', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('01', '01', 'Ações coletivas/individuais em saúde', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('09', '01', 'Atenção em Oncologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('07', '01', 'Órteses, próteses e materiais especiais não relacionados ao ato cirúrgico', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('06', '01', 'Medicamentos de dispensação excepcional', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '01', 'Consultas / Atendimentos / Acompanhamentos', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('08', '01', 'Ações relacionadas ao estabelecimento', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '02', 'Fisioterapia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '02', 'Diagnóstico em laboratório clínico', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('01', '02', 'Vigilância em saúde', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('09', '02', 'Atenção em Cardiologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('08', '02', 'Ações relacionadas ao atendimento', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('07', '02', 'Órteses, próteses e materiais especiais relacionados ao ato cirúrgico', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('06', '02', 'Medicamentos estratégicos', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('05', '02', 'Avaliação de morte encefálica', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '02', 'Cirurgia de glândulas endócrinas', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '03', 'Diagnóstico por anatomia patológica e citopatologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('09', '03', 'Atenção em Ortopedia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('08', '03', 'Autorização / regulação', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('05', '03', 'Ações relacionadas à doação de orgãos e tecidos para transplante', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '03', 'Cirurgia do sistema nervoso central e periférico', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '03', 'Tratamentos clínicos (outras especialidades)', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('06', '03', 'Medicamentos de âmbito hospitalar e urgência', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '04', 'Diagnóstico por radiologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('06', '04', 'Componente especializado da assistência farmacêutica', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('05', '04', 'Processamento de tecidos para transplante', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('08', '04', 'Telessaúde', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('09', '04', 'Atenção em Otorrinolaringologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '04', 'Tratamento em oncologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '04', 'Cirurgia das vias aéreas superiores, da face, da cabeça e do pescoço', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('05', '05', 'Transplante de orgãos, tecidos e células', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '05', 'Diagnóstico por ultrasonografia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '05', 'Cirurgia do aparelho da visão', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('09', '05', 'Atenção em Oftalmologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '05', 'Tratamento em nefrologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '06', 'Diagnóstico por tomografia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '06', 'Hemoterapia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '06', 'Cirurgia do aparelho circulatório', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('05', '06', 'Acompanhamento e intercorrências no pré e pós-transplante', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('09', '06', 'Atenção em Saúde Mulher', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '07', 'Diagnóstico por ressonância magnética', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '07', 'Tratamentos odontológicos', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '07', 'Cirurgia do aparelho digestivo, orgãos anexos e parede abdominal', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '08', 'Cirurgia do sistema osteomuscular', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '08', 'Diagnóstico por medicina nuclear in vivo', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '08', 'Tratamento de lesões, envenenamentos e outros, decorrentes de causas externas', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '09', 'Cirurgia do aparelho geniturinário', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '09', 'Diagnóstico por endoscopia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '09', 'Terapias especializadas', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '10', 'Parto e nascimento', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '10', 'Diagnóstico por radiologia intervencionista', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '10', 'Cirurgia de mama', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '11', 'Métodos diagnósticos em especialidades', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('03', '11', 'Cuidados Paliativos', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '11', 'Cirurgia obstétrica', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '12', 'Cirurgia torácica', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '12', 'Diagnóstico e procedimentos especiais em hemoterapia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '13', 'Diagnóstico em vigilância epidemiológica e ambiental', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '13', 'Cirurgia reparadora', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '14', 'Bucomaxilofacial', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('02', '14', 'Diagnóstico por teste rápido', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '15', 'Outras cirurgias', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '16', 'Cirurgia em oncologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '17', 'Anestesiologia', '202507', 1);
INSERT INTO public."tb_sub_grupo" ("co_grupo", "co_sub_grupo", "no_sub_grupo", "dt_competencia", "version_id") VALUES ('04', '18', 'Cirurgia em nefrologia', '202507', 1);
